version: 2

jobs:
  bionic:
    docker:
      - image: vapor/swift:5.1-bionic
    steps:
      - checkout
      - run: apt-get update; apt-get install -y libssl-dev zlib1g-dev
      - run: swift build
      - run: swift test
  bionic-release:
    docker:
      - image: vapor/swift:5.1-bionic
    steps:
      - checkout
      - run: apt-get update; apt-get install -y libssl-dev zlib1g-dev
      - run: swift build -c release

workflows:
  version: 2
  tests:
    jobs:
      - bionic
      - bionic-release