#if !canImport(ObjectiveC)
import XCTest

extension HistogramTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HistogramTests = [
        ("testHistogramStandalone", testHistogramStandalone),
        ("testHistogramSwiftMetrics", testHistogramSwiftMetrics),
        ("testHistogramTime", testHistogramTime),
    ]
}

extension PrometheusMetricsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PrometheusMetricsTests = [
        ("testCollectAFewMetricsIntoBuffer", testCollectAFewMetricsIntoBuffer),
        ("testCollectAFewMetricsIntoString", testCollectAFewMetricsIntoString),
        ("testCollectIntoBuffer", testCollectIntoBuffer),
        ("testCounter", testCounter),
        ("testGauge", testGauge),
        ("testMetricDestroying", testMetricDestroying),
    ]
}

extension SummaryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SummaryTests = [
        ("testSummary", testSummary),
        ("testSummaryStandalone", testSummaryStandalone),
        ("testSummaryTime", testSummaryTime),
        ("testSummaryWithPreferredDisplayUnit", testSummaryWithPreferredDisplayUnit),
    ]
}

extension SwiftPrometheusTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftPrometheusTests = [
        ("testCounter", testCounter),
        ("testGauge", testGauge),
        ("testMultipleCounter", testMultipleCounter),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HistogramTests.__allTests__HistogramTests),
        testCase(PrometheusMetricsTests.__allTests__PrometheusMetricsTests),
        testCase(SummaryTests.__allTests__SummaryTests),
        testCase(SwiftPrometheusTests.__allTests__SwiftPrometheusTests),
    ]
}
#endif
