#if !canImport(ObjectiveC)
import XCTest

extension GaugeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GaugeTests = [
        ("testGaugeStandalone", testGaugeStandalone),
        ("testGaugeSwiftMetrics", testGaugeSwiftMetrics),
        ("testGaugeTime", testGaugeTime),
    ]
}

extension HistogramTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HistogramTests = [
        ("testHistogramStandalone", testHistogramStandalone),
        ("testHistogramSwiftMetrics", testHistogramSwiftMetrics),
        ("testHistogramTime", testHistogramTime),
    ]
}

extension PrometheusMetricsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PrometheusMetricsTests = [
        ("testCollectAFewMetricsIntoBuffer", testCollectAFewMetricsIntoBuffer),
        ("testCollectAFewMetricsIntoString", testCollectAFewMetricsIntoString),
        ("testCollectIntoBuffer", testCollectIntoBuffer),
        ("testCounter", testCounter),
        ("testMetricDestroying", testMetricDestroying),
        ("testSummary", testSummary),
        ("testSummaryWithPreferredDisplayUnit", testSummaryWithPreferredDisplayUnit),
    ]
}

extension SwiftPrometheusTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftPrometheusTests = [
        ("testCounter", testCounter),
        ("testMultipleCounter", testMultipleCounter),
        ("testSummary", testSummary),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GaugeTests.__allTests__GaugeTests),
        testCase(HistogramTests.__allTests__HistogramTests),
        testCase(PrometheusMetricsTests.__allTests__PrometheusMetricsTests),
        testCase(SwiftPrometheusTests.__allTests__SwiftPrometheusTests),
    ]
}
#endif
